version: '3.1'

services:
  mongo:
    image: mongo
    networks:
      - backend
    deploy:
      placement:
        constraints: [node.role == manager]
  app:
    image: ahmadulinjs/todo-app
    ports:
      - "8081:8081"
    environment:
      - DB_URL=mongodb://mongo:27017
    depends_on:
      - mongo
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
      restart_policy:
        condition: on-failure
    networks:
      - backend
networks:
  backend: